version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    cooldown:
      default-days: 7
      include:
        - "*"
    groups:
      minor:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    cooldown:
      default-days: 14
    groups:
      all:
        patterns:
          - "*"
