name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: ruby/setup-ruby@v1.313.0
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails-8-0
          - gemfiles/rails-8-1
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: ruby/setup-ruby@v1.313.0
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - env:
          RAILS_ENV: test
        run: bin/rails-test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: ruby/setup-ruby@v1.313.0
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: |
          bundle config set --global path "$PWD/vendor/bundle"
          BUNDLE_GEMFILE=gemfiles/rails-8-0 bundle install --jobs 4
          BUNDLE_GEMFILE=gemfiles/rails-8-1 bundle install --jobs 4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: corepack enable
      - run: bin/test-e2e
